### ISSUE TITLE
Error when opening podcasts section

### ISSUE THREAD

**Issue by karrukola** [karrukola/plugin.audio.deejayIt.reloaded#15]
```
22:57:20 T:6316   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\xb2' in position 2: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "C:\Users\filip\AppData\Roaming\Kodi\addons\plugin.audio.deejayIt.reloaded\default.py", line 73, in <module>
                                                'showThumb': prog[1]})
                                              File "C:\Users\filip\AppData\Roaming\Kodi\addons\plugin.audio.deejayIt.reloaded\default.py", line 39, in build_url
                                                return BASE_URL + '?' + urllib.urlencode(query)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib.py", line 1332, in urlencode
                                                v = quote_plus(str(v))
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xb2' in position 2: ordinal not in range(128)
                                            -->End of Python script error report<--
22:57:20 T:1396   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.audio.deejayIt.reloaded/?mode=reloaded
22:57:20 T:1396   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.deejayIt.reloaded/?mode=reloaded) failed
```

**Comment by karrukola** [comment]
`23:00:18 T:6044   DEBUG: XFILE::CPluginDirectory::StartScript - calling plugin DeeJay reloaded('plugin://plugin.audio.deejayIt.reloaded/','3','')
23:00:18 T:220   DEBUG: Thread LanguageInvoker start, auto delete: false
23:00:18 T:220    INFO: initializing python engine.
23:00:18 T:220   DEBUG: CPythonInvoker(4, C:\Users\filip\AppData\Roaming\Kodi\addons\plugin.audio.deejayIt.reloaded\default.py): start processing
23:00:18 T:220   DEBUG: -->Python Interpreter Initialized<--
23:00:18 T:220   DEBUG: CPythonInvoker(4, C:\Users\filip\AppData\Roaming\Kodi\addons\plugin.audio.deejayIt.reloaded\default.py): the source file to load is "C:\Users\filip\AppData\Roaming\Kodi\addons\plugin.audio.deejayIt.reloaded\default.py"
23:00:18 T:220   DEBUG: CPythonInvoker(4, C:\Users\filip\AppData\Roaming\Kodi\addons\plugin.audio.deejayIt.reloaded\default.py): setting the Python path to C:\Users\filip\AppData\Roaming\Kodi\addons\plugin.audio.deejayIt.reloaded;C:\Users\filip\AppData\Roaming\Kodi\addons\script.module.beautifulsoup\lib;C:\Program Files (x86)\Kodi\system\python\DLLs;C:\Program Files (x86)\Kodi\system\python\Lib;C:\Program Files (x86)\Kodi\python27.zip;C:\Program Files (x86)\Kodi\system\python\lib\plat-win;C:\Program Files (x86)\Kodi\system\python\lib\lib-tk;C:\Program Files (x86)\Kodi;C:\Program Files (x86)\Kodi\system\python;C:\Program Files (x86)\Kodi\system\python\lib\site-packages
23:00:18 T:220   DEBUG: CPythonInvoker(4, C:\Users\filip\AppData\Roaming\Kodi\addons\plugin.audio.deejayIt.reloaded\default.py): entering source directory C:\Users\filip\AppData\Roaming\Kodi\addons\plugin.audio.deejayIt.reloaded
23:00:18 T:220   DEBUG: CPythonInvoker(4, C:\Users\filip\AppData\Roaming\Kodi\addons\plugin.audio.deejayIt.reloaded\default.py): instantiating addon using automatically obtained id of "plugin.audio.deejayIt.reloaded" dependent on version 2.1.0 of the xbmc.python api
23:00:18 T:220    INFO: CPythonInvoker(4, C:\Users\filip\AppData\Roaming\Kodi\addons\plugin.audio.deejayIt.reloaded\default.py): script successfully run
23:00:18 T:220    INFO: Python script stopped
23:00:18 T:220   DEBUG: Thread LanguageInvoker 220 terminating
23:00:18 T:6044   DEBUG: XFILE::CPluginDirectory::WaitOnScriptResult - waiting on the DeeJay reloaded (id=4) plugin...
23:00:18 T:6044   DEBUG: XFILE::CPluginDirectory::WaitOnScriptResult- plugin returned successfully
23:00:18 T:1396   DEBUG: RetrieveMusicInfo() took 0 msec
23:00:18 T:4164   DEBUG: Thread BackgroundLoader start, auto delete: false
23:00:18 T:4164   DEBUG: Thread BackgroundLoader 4164 terminating
23:00:19 T:1396   DEBUG: Keyboard: scancode: 0x1c, sym: 0x000d, unicode: 0x000d, modifier: 0x0
23:00:19 T:1396   DEBUG: CInputManager::OnKey: return (0xf00d) pressed, action is Select
23:00:19 T:1396   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.audio.deejayIt.reloaded/?mode=reloaded)
23:00:19 T:1396   DEBUG:   ParentPath = [plugin://plugin.audio.deejayIt.reloaded/]
23:00:19 T:6044   DEBUG: XFILE::CPluginDirectory::StartScript - calling plugin DeeJay reloaded('plugin://plugin.audio.deejayIt.reloaded/','4','?mode=reloaded')
23:00:19 T:6044   DEBUG: XFILE::CPluginDirectory::WaitOnScriptResult - waiting on the DeeJay reloaded (id=5) plugin...
23:00:19 T:3600   DEBUG: Thread LanguageInvoker start, auto delete: false
23:00:19 T:3600    INFO: initializing python engine.
23:00:19 T:3600   DEBUG: CPythonInvoker(5, C:\Users\filip\AppData\Roaming\Kodi\addons\plugin.audio.deejayIt.reloaded\default.py): start processing
23:00:19 T:3600   DEBUG: -->Python Interpreter Initialized<--
23:00:19 T:3600   DEBUG: CPythonInvoker(5, C:\Users\filip\AppData\Roaming\Kodi\addons\plugin.audio.deejayIt.reloaded\default.py): the source file to load is "C:\Users\filip\AppData\Roaming\Kodi\addons\plugin.audio.deejayIt.reloaded\default.py"
23:00:19 T:3600   DEBUG: CPythonInvoker(5, C:\Users\filip\AppData\Roaming\Kodi\addons\plugin.audio.deejayIt.reloaded\default.py): setting the Python path to C:\Users\filip\AppData\Roaming\Kodi\addons\plugin.audio.deejayIt.reloaded;C:\Users\filip\AppData\Roaming\Kodi\addons\script.module.beautifulsoup\lib;C:\Program Files (x86)\Kodi\system\python\DLLs;C:\Program Files (x86)\Kodi\system\python\Lib;C:\Program Files (x86)\Kodi\python27.zip;C:\Program Files (x86)\Kodi\system\python\lib\plat-win;C:\Program Files (x86)\Kodi\system\python\lib\lib-tk;C:\Program Files (x86)\Kodi;C:\Program Files (x86)\Kodi\system\python;C:\Program Files (x86)\Kodi\system\python\lib\site-packages
23:00:19 T:3600   DEBUG: CPythonInvoker(5, C:\Users\filip\AppData\Roaming\Kodi\addons\plugin.audio.deejayIt.reloaded\default.py): entering source directory C:\Users\filip\AppData\Roaming\Kodi\addons\plugin.audio.deejayIt.reloaded
23:00:19 T:3600   DEBUG: CPythonInvoker(5, C:\Users\filip\AppData\Roaming\Kodi\addons\plugin.audio.deejayIt.reloaded\default.py): instantiating addon using automatically obtained id of "plugin.audio.deejayIt.reloaded" dependent on version 2.1.0 of the xbmc.python api
23:00:20 T:1396   DEBUG: ------ Window Init (DialogBusy.xml) ------
23:00:21 T:3600   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\xb2' in position 2: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "C:\Users\filip\AppData\Roaming\Kodi\addons\plugin.audio.deejayIt.reloaded\default.py", line 73, in <module>
                                                'showThumb': prog[1]})
                                              File "C:\Users\filip\AppData\Roaming\Kodi\addons\plugin.audio.deejayIt.reloaded\default.py", line 39, in build_url
                                                return BASE_URL + '?' + urllib.urlencode(query)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib.py", line 1332, in urlencode
                                                v = quote_plus(str(v))
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xb2' in position 2: ordinal not in range(128)
                                            -->End of Python script error report<--
23:00:21 T:1396   DEBUG: ------ Window Init (DialogKaiToast.xml) ------
23:00:21 T:3600    INFO: Python script stopped
23:00:21 T:3600   DEBUG: Thread LanguageInvoker 3600 terminating
23:00:21 T:6044   DEBUG:  XFILE::CPluginDirectory::WaitOnScriptResult - plugin exited prematurely - terminating
23:00:21 T:1396   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.audio.deejayIt.reloaded/?mode=reloaded
23:00:21 T:1396   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.deejayIt.reloaded/?mode=reloaded) failed
23:00:21 T:1396   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.audio.deejayIt.reloaded/)
23:00:21 T:1396   DEBUG:   ParentPath = [addons://sources/audio]
23:00:21 T:6044   DEBUG: XFILE::CPluginDirectory::StartScript - calling plugin DeeJay reloaded('plugin://plugin.audio.deejayIt.reloaded/','5','')
23:00:21 T:6044   DEBUG: XFILE::CPluginDirectory::WaitOnScriptResult - waiting on the DeeJay reloaded (id=6) plugin...
23:00:21 T:2380   DEBUG: Thread LanguageInvoker start, auto delete: false
23:00:21 T:2380    INFO: initializing python engine.
23:00:21 T:2380   DEBUG: CPythonInvoker(6, C:\Users\filip\AppData\Roaming\Kodi\addons\plugin.audio.deejayIt.reloaded\default.py): start processing
23:00:21 T:2380   DEBUG: -->Python Interpreter Initialized<--
23:00:21 T:2380   DEBUG: CPythonInvoker(6, C:\Users\filip\AppData\Roaming\Kodi\addons\plugin.audio.deejayIt.reloaded\default.py): the source file to load is "C:\Users\filip\AppData\Roaming\Kodi\addons\plugin.audio.deejayIt.reloaded\default.py"
23:00:21 T:2380   DEBUG: CPythonInvoker(6, C:\Users\filip\AppData\Roaming\Kodi\addons\plugin.audio.deejayIt.reloaded\default.py): setting the Python path to C:\Users\filip\AppData\Roaming\Kodi\addons\plugin.audio.deejayIt.reloaded;C:\Users\filip\AppData\Roaming\Kodi\addons\script.module.beautifulsoup\lib;C:\Program Files (x86)\Kodi\system\python\DLLs;C:\Program Files (x86)\Kodi\system\python\Lib;C:\Program Files (x86)\Kodi\python27.zip;C:\Program Files (x86)\Kodi\system\python\lib\plat-win;C:\Program Files (x86)\Kodi\system\python\lib\lib-tk;C:\Program Files (x86)\Kodi;C:\Program Files (x86)\Kodi\system\python;C:\Program Files (x86)\Kodi\system\python\lib\site-packages
23:00:21 T:2380   DEBUG: CPythonInvoker(6, C:\Users\filip\AppData\Roaming\Kodi\addons\plugin.audio.deejayIt.reloaded\default.py): entering source directory C:\Users\filip\AppData\Roaming\Kodi\addons\plugin.audio.deejayIt.reloaded
23:00:21 T:2380   DEBUG: CPythonInvoker(6, C:\Users\filip\AppData\Roaming\Kodi\addons\plugin.audio.deejayIt.reloaded\default.py): instantiating addon using automatically obtained id of "plugin.audio.deejayIt.reloaded" dependent on version 2.1.0 of the xbmc.python api
23:00:21 T:6044   DEBUG: XFILE::CPluginDirectory::WaitOnScriptResult- plugin returned successfully
23:00:21 T:2380    INFO: CPythonInvoker(6, C:\Users\filip\AppData\Roaming\Kodi\addons\plugin.audio.deejayIt.reloaded\default.py): script successfully run
23:00:21 T:1396   DEBUG: RetrieveMusicInfo() took 0 msec`

**Comment by karrukola** [comment]
Mortacci tua, Matteo Curti, con MC^2 - che neanche riesco a scrivere bene con questa tastiera.

`21:35:43 T:8520   DEBUG: ###############
21:35:43 T:8520   DEBUG: 25
21:35:43 T:8520   DEBUG: Laura Antonini
21:35:43 T:8520   DEBUG: http://cdn.gelestatic.it/deejay/www/2013/06/Laura-Antonini-150x150.jpg
21:35:43 T:8520   DEBUG: http://www.deejay.it/audio/20160828/493250/
21:35:43 T:8520   DEBUG: 28.08.2016
21:35:43 T:8520   DEBUG: ###############
21:35:43 T:8520   DEBUG: 26
21:35:43 T:8520   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\xb2' in position 2: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "C:\Users\Filippo\AppData\Roaming\Kodi\addons\plugin.audio.deejayIt.reloaded\default.py", line 73, in <module>
                                                xbmc.log(msg=str(pr), level=xbmc.LOGDEBUG)
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xb2' in position 2: ordinal not in range(128)
                                            -->End of Python script error report<--
21:35:43 T:8520    INFO: Python script stopped
`
